language: python

matrix:
  include:
    - python: 3.3
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: nightly
  fast_finish: true
  allow_failures:
    - python: nightly

install:
  - pip install six
  - pip install -e .
  - python -m elm_kernel.install
  - pip install -r tests/requirements.txt

script:
  - cd tests
  - jupyter nbconvert --execute --inplace --to notebook test.ipynb
